# Generated by Django 3.2.11 on 2023-05-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_shoppinglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
