# Generated by Django 3.2.11 on 2023-05-17 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_subscription_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='HEX code', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате HEX-кода', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цветовой HEX-код'),
        ),
    ]
