# Generated by Django 3.2.11 on 2023-05-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
