# Generated by Django 3.2.11 on 2023-05-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20230520_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
