# Generated by Django 3.2.11 on 2023-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230502_0846'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique email and username',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'username'), name='unique_email_and_username'),
        ),
    ]
